/* Generated By:JavaCC: Do not edit this line. GrammarConstants.java */
package sics.seiois.ei.grammar;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface GrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MULTIPLY = 8;
  /** RegularExpression Id. */
  int DIVIDE = 9;
  /** RegularExpression Id. */
  int T_OPEN_SB = 10;
  /** RegularExpression Id. */
  int T_CLOSE_SB = 11;
  /** RegularExpression Id. */
  int T_DEDUCTION = 12;
  /** RegularExpression Id. */
  int T_EQUAL = 13;
  /** RegularExpression Id. */
  int T_EQUAL2 = 14;
  /** RegularExpression Id. */
  int T_NOTEQUAL = 15;
  /** RegularExpression Id. */
  int T_NOTEQUAL2 = 16;
  /** RegularExpression Id. */
  int T_SINGLE_Q = 17;
  /** RegularExpression Id. */
  int T_COMMA = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int CONSTANT = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int LETTER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"->\"",
    "\"=\"",
    "\"==\"",
    "\"<>\"",
    "\"!=\"",
    "\"\\\'\"",
    "\",\"",
    "<IDENTIFIER>",
    "<CONSTANT>",
    "<DIGIT>",
    "<LETTER>",
    "\"REE:\"",
    "\".\"",
  };

}
