//
// Generated by JTB 1.3.2
//

package oo.syntaxtree;

/**
 * Grammar production:
 * f0 -> MultiplicativeExpression()
 * f1 -> ( ( "+" | "-" ) MultiplicativeExpression() )*
 */
@SuppressWarnings("all")
public class AdditiveExpression implements Node {
   public MultiplicativeExpression f0;
   public NodeListOptional f1;

   public AdditiveExpression(MultiplicativeExpression n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(oo.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(oo.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(oo.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(oo.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

