//
// Generated by JTB 1.3.2
//

package oo.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
@SuppressWarnings("all")
public interface Node extends java.io.Serializable {
   public void accept(oo.visitor.Visitor v);
   public <R,A> R accept(oo.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(oo.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(oo.visitor.GJVoidVisitor<A> v, A argu);
}

